"""Initial migrations One

Revision ID: 0f85b4c82623
Revises: 
Create Date: 2025-03-13 20:04:45.725699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f85b4c82623'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('c_password', sa.String(length=255), nullable=False),
    sa.Column('_is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_data',
    sa.Column('condition_code', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('localtime', sa.DateTime(), nullable=False),
    sa.Column('temp_c', sa.Float(), nullable=False),
    sa.Column('wind_kph', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('feelslike_c', sa.Float(), nullable=False),
    sa.Column('cloud', sa.Float(), nullable=False),
    sa.Column('condition', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('condition_code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('weather_data1',
    sa.Column('condition_code', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('temp_c', sa.String(length=100), nullable=False),
    sa.Column('wind_kph', sa.String(length=100), nullable=False),
    sa.Column('humidity', sa.String(length=100), nullable=False),
    sa.Column('feelslike_c', sa.String(length=100), nullable=False),
    sa.Column('condition', sa.String(length=100), nullable=False),
    sa.Column('condition_icon', sa.String(length=100), nullable=True),
    sa.Column('localtime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name', 'condition_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_data1')
    op.drop_table('weather_data')
    op.drop_table('User')
    # ### end Alembic commands ###
